name: Deploy to Personal Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2

    - name: Setup SSH keys
      uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.WORKER_SECRET }}
      run: |
        ssh-keyscan freedom.dementor.info >> ~/.ssh/known_hosts

    - name: Build Docker image
      run: |
        docker build -t my-image "./WebDevelopment/22 todolist-v1"

    - name: Tag Docker image
      run: |
        docker tag my-image username/my-image:latest

    - name: Push to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        docker push username/my-image:latest

    - name: Deploy to server
      env:
        SSH_AUTH_SOCK: /tmp/ssh-socket
      run: |
        ssh-add -D # Removes all keys so we only use the newly added one
        ssh-add <(echo "$WORKER_SECRET")
        ssh -o StrictHostKeyChecking=no -A worker@freedom.dementor.info \
        "docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD} && \
        docker stop my-container || true && \
        docker rm my-container || true && \
        docker pull username/my-image:latest && \
        docker run -d -p 8080:8080 --name my-container username/my-image:latest"
