name: Build and Deploy to freedom.dementor.info

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: freedom.dementor.info:8080
        username: worker
        password: ${{ secrets.WORKER_SECRET }}
        insecure: true

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: freedom.dementor.info:8080/${{ github.repository }}:latest

    - name: SSH into the server and redeploy the container
      uses: appleboy/ssh-action@master
      with:
        host: freedom.dementor.info
        username: worker
        password: ${{ secrets.WORKER_SECRET }}
        script: |
          docker stop ${DOCKER_CONTAINER_NAME} || true
          docker rm ${DOCKER_CONTAINER_NAME} || true
          docker pull freedom.dementor.info:8080/${{ github.repository }}:latest
          docker run -d -p ${DOCKER_PORT}:3001 --name ${DOCKER_CONTAINER_NAME} freedom.dementor.info:8080/${{ github.repository }}:latest

    env:
      DOCKER_CONTAINER_NAME: "my-node-app"
      DOCKER_PORT: "8081"
