name: Deploy to Personal Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2

    - name: Setup SSH keys
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.WORKER_SECRET }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan freedom.dementor.info >> ~/.ssh/known_hosts

    - name: Build Docker image
      run: |
        docker build -t my-image "./WebDevelopment/22 todolist-v1"

    - name: Tag Docker image
      run: |
        docker tag my-image username/my-image:latest

    - name: Push to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        docker push username/my-image:latest

    - name: Deploy to server
      env:
        WORKER_SECRET: ${{ secrets.WORKER_SECRET }}
      run: |
        ssh worker@freedom.dementor.info \
        "docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD} && \
        docker stop my-container || true && \
        docker rm my-container || true && \
        docker pull username/my-image:latest && \
        docker run -d -p 80:80 --name my-container username/my-image:latest"
